### ISSUE TITLE
This image is fairly heavy...

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-mtbls-dwnld#1]
Can I suggest that you follow [this recommendation](https://github.com/phnmnl/phenomenal-h2020/wiki/Dockerfile-Guide#reduce-image-size-by-multiple-line-runs) to reduce the size of the image? Having the cleaning lines (apt-get purge, rm -rf directories, etc) has no impact if it is done on a separate RUN line. You should be able to purge all -dev packages, g++ (which will get rid of gcc) and others that are only needed for the compilation of Risa, but then not needed anymore. Currently your image is about 853 MB, I'm sure that you should be able to get below 200 MB by compacting run statements and purging compilation only packages post installation of things that require compilation.

Thanks!

**Comment by pkrog** [comment]
You're right. I was just postponing it.

**Comment by pkrog** [comment]
I've made modifications, the size is now 600MB. I did not remove libraries since they were required by Risa installation (well, its dependencies) and I don't know if they can be used at some point or not.

**Comment by pcm32** [comment]
Fantastic, thanks! I normally get rid of all the -devs and works fine (all the tests). My understanding is that compiled R packages links everything inside. What I have tried as well is to install r-base-dev, make all the package compilations, and then remove r-base-dev, and works like a charm unless that the package does some compilation when processing data, but that is fairly uncommon for what I have seen. But once we have some tests, we can try removing them and see how it goes!
