### ISSUE TITLE
Aspera download fails for MTBLS38

### ISSUE THREAD

**Issue by sneumann** [phnmnl/container-mtbls-dwnld#2]
Hi, trying to download MTBLS38 fails with:
```

==== Pod galaxy-7362-67slj log start ====

2018-02-16T13:24:42.480869267Z ERROR: Downloading of study MTBLS38 has failed.
2018-02-16T13:24:42.516053877Z mv: missing destination file operand after '/opt/galaxy_data/database/job_working_directory/007/7362/dataset_21329_files'
2018-02-16T13:24:42.516070307Z Try 'mv --help' for more information.


==== Pod galaxy-7362-67slj log end   ====
```

**Comment by pkrog** [comment]
Hi @sneumann ,

I've reproduced your error when not using a token.
Did you use a token when running the tool?
Aspera requires a token for private studies as well as public ones.
It worked for me with the public token @khaug gave me once.

I'll update the tool so the message is clearer in case user forget to set the token.

**Comment by sneumann** [comment]
Could you use this logic https://github.com/phnmnl/container-galaxy-k8s-runtime/blob/develop/tools/phenomenal/transfer/metabolights-downloader.xml#L6
for public studies ?

**Comment by pkrog** [comment]
Sure, I didn't know it was a real public public token. @khaug gave it to us once, but I was not sure I could put it inside a script. Are you ok with that @khaug?

**Comment by khaug** [comment]
Sure, we have no problems with releasing the public key/password, this Aspera server can only see the public data. This is equivalent to anonymous FTP.

**Comment by pkrog** [comment]
Thanks, I'll make the modifications then.
